# Copyright (c) 2017-2021 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
version: 2
jobs:
  build:
    docker:
      # The browsers image has both Python and Java; we need both
      - image: cimg/python:3.6.13-browsers
        
    resource_class: medium+
    steps:
      - checkout

      - restore_cache:
          key: jq-{{ checksum ".circleci/install-jq" }}
      - run:
          command: .circleci/install-jq
      - save_cache:
          key: jq-{{ checksum ".circleci/install-jq" }}
          paths: /home/circleci/.jq

      - restore_cache:
          key: daml-{{ checksum ".circleci/install-daml" }}
      - run:
          command: .circleci/install-daml
      - save_cache:
          key: daml-{{ checksum ".circleci/install-daml" }}
          paths: /home/circleci/.daml

      - restore_cache:
          key: deps-{{ checksum "python/poetry.lock" }}
      - run:
          command: poetry config virtualenvs.in-project true && make -C python deps
      - save_cache:
          key: deps-{{ checksum "python/poetry.lock" }}
          paths: "python/.venv"

      - run:
          name: Python format checks
          command: make python-format-check
      - run:
          name: Python unit tests
          command: make python-test
      - run:
          name: Python integration tests
          command: make python-integration-test
      - run:
          name: Python packaging
          command: make -C python package
      - store_test_results:
          path: python/test-results
  blackduck:
    docker:
      - image: rappdw/docker-java-python
    steps:
      - checkout

      - restore_cache:
          key: jq-{{ checksum ".circleci/install-jq" }}
      - run:
          command: .circleci/install-jq
      - save_cache:
          key: jq-{{ checksum ".circleci/install-jq" }}
          paths: /home/circleci/.jq

      - run:
          name: Run Blackduck Detect
          command: |
            cp /home/circleci/.jq/bin/jq /usr/local/bin
            bash <(curl -s https://raw.githubusercontent.com/DACH-NY/security-blackduck/master/synopsys-detect) ci-build digitalasset_dazl master --logging.level.com.synopsys.integration=DEBUG --detect.python.python3=true
          working_directory: python
          
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - blackduck:
          context: blackduck
